name: client
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.2
  protos:
    path: protos

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true