name: server
description: A simple command-line application.
version: 0.0.1+0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  grpc: ^3.0.2
  protos:
    path: protos

dev_dependencies:
  lints: ^1.0.0
